# Generated by Django 3.2.7 on 2022-05-21 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100, null=True)),
                ('apartment_address', models.CharField(max_length=100, null=True)),
                ('City', models.TextField(null=True)),
                ('State', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('zip', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Body_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Company_Name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Fuel_Type', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Model_Name', models.TextField(null=True)),
                ('Company_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsifydealers.car_company')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('City', models.TextField(null=True)),
                ('State', models.TextField(null=True)),
                ('Query', models.TextField(null=True)),
                ('Remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='India_States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_Name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Individual_Car_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.TextField(null=True)),
                ('Car_Status', models.BooleanField(default=False)),
                ('Date_of_Manufacturing', models.DateField(null=True)),
                ('Card_Registration_Number', models.TextField(null=True)),
                ('Car_Varient', models.TextField(null=True)),
                ('KM', models.IntegerField(null=True)),
                ('Showimage', models.ImageField(upload_to='')),
                ('Color', models.TextField(null=True)),
                ('Price', models.IntegerField(null=True)),
                ('Insurance', models.TextField(null=True)),
                ('Insurance_Type', models.TextField(null=True)),
                ('Discription', models.TextField(null=True)),
                ('showB2C', models.BooleanField(default=False)),
                ('Body_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsifydealers.car_body_type')),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsifydealers.car_company')),
                ('Fuel_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsifydealers.car_fuel')),
                ('Model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsifydealers.car_model')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Number_of_Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owners', models.IntegerField(null=True)),
                ('Postfix', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tranmission', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileImg', models.FileField(null=True, upload_to='')),
                ('ContactNo', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('isDealer', models.BooleanField(default='False')),
                ('AddharNumber', models.IntegerField(default=0, null=True)),
                ('PanNumber', models.TextField(null=True)),
                ('VoterID', models.TextField(null=True)),
                ('Address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsifydealers.address')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavouriteCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsifydealers.individual_car_details')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Individual_Car_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('carid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsifydealers.individual_car_details')),
            ],
        ),
        migrations.AddField(
            model_name='individual_car_details',
            name='Owners',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsifydealers.number_of_owners'),
        ),
        migrations.AddField(
            model_name='individual_car_details',
            name='Registration_State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsifydealers.india_states'),
        ),
        migrations.AddField(
            model_name='individual_car_details',
            name='Transmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsifydealers.transmission_type'),
        ),
        migrations.AddField(
            model_name='individual_car_details',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DealerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=12)),
                ('Document', models.FileField(upload_to='media/dealerApplications/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('Company_Name', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('Document', models.FileField(upload_to='media/dealers/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='Address_Typee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsifydealers.address_type'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
