# Generated by Django 3.2.7 on 2022-06-07 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carsifydealers', '0002_gumasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gumasta',
            name='gumsata',
            field=models.FileField(upload_to='media/dealerApplications/'),
        ),
        migrations.AlterField(
            model_name='gumasta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
